export const petsSeed = [
    {
        "id": "pet_1",
        "name": "Buddy",
        "age": "3",
        "sex": "male",
        "size": "small",
        "photos": ["https://www.petz.com.br/blog/wp-content/uploads/2019/03/cachorro-mini-pet.jpg"],
        "weight": "5",
        "description": "Cute and fluffy with a curly tail",
        "behavior": "friendly",
        "observations": "Enjoys long walks in the park"
    },
    {
        "id": "pet_2",
        "name": "Luna",
        "age": "2",
        "sex": "female",
        "size": "medium",
        "photos": ["https://s2.glbimg.com/nvjFq8VRjyrpdQqaOeywz-5DFwY=/e.glbimg.com/og/ed/f/original/2021/08/27/captura_de_tela_2021-08-27_as_11.01.15.png"],
        "weight": "6",
        "description": "Sleek black coat with bright eyes",
        "behavior": "playful",
        "observations": "Loves playing fetch"
    },
    {
        "id": "pet_3",
        "name": "Max",
        "age": "4",
        "sex": "male",
        "size": "large",
        "photos": ["https://assets.elanco.com/8e0bf1c2-1ae4-001f-9257-f2be3c683fb1/45739ea8-eff3-40ce-b074-23e2cee6ac21/cachorro-cachecol-frio-inverno_0.jpg?w=3840&q=75&auto=format"],
        "weight": "10",
        "description": "Golden retriever with a friendly demeanor",
        "behavior": "calm",
        "observations": "Gets along well with other dogs"
    },
    {
        "id": "pet_4",
        "name": "Zoe",
        "age": "1",
        "sex": "female",
        "size": "small",
        "photos": ["https://uploads.metropoles.com/wp-content/uploads/2022/05/02141436/conheca_as_racas_de_cachorros_mais_inteligentes_widexl-600x400.jpg"],
        "weight": "4",
        "description": "White fur with brown spots on ears",
        "behavior": "energetic",
        "observations": "Needs a lot of playtime"
    },
    {
        "id": "pet_5",
        "name": "Rocky",
        "age": "5",
        "sex": "male",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk8mRK6O7EbmqaTqZJB5RuDe-4HoX54a3gHw&usqp=CAU"],
        "weight": "8",
        "description": "Brindle coat with a playful personality",
        "behavior": "friendly",
        "observations": "Loves to chase butterflies"
    },
    {
        "id": "pet_6",
        "name": "Mia",
        "age": "2",
        "sex": "female",
        "size": "large",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrN9wYXY_u7o5AVq_HI7cb8ICjQfYZh17SDA&usqp=CAU"],
        "weight": "9",
        "description": "Black and tan coat with a wagging tail",
        "behavior": "loving",
        "observations": "Enjoys cuddling on the couch"
    },
    {
        "id": "pet_7",
        "name": "Charlie",
        "age": "3",
        "sex": "male",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ-uhHxlukNKnbKh4Xvn7gmVCL0i_kiA0QRg&usqp=CAU"],
        "weight": "7",
        "description": "Fluffy golden fur with a friendly bark",
        "behavior": "playful",
        "observations": "Likes playing with squeaky toys"
    },
    {
        "id": "pet_8",
        "name": "Sophie",
        "age": "1",
        "sex": "female",
        "size": "small",
        "photos": ["https://www.petz.com.br/blog//wp-content/uploads/2019/06/cachorro-filhote.jpg"],
        "weight": "3",
        "description": "Small and adorable with a sweet personality",
        "behavior": "gentle",
        "observations": "Great with children"
    },
    {
        "id": "pet_9",
        "name": "Bentley",
        "age": "4",
        "sex": "male",
        "size": "large",
        "photos": ["https://www.bnews.com.br/media/_versions/junho_2022/cachorro_pequeno_widemd.jpeg"],
        "weight": "12",
        "description": "Sturdy build with a brindle coat",
        "behavior": "loyal",
        "observations": "Protective of his family"
    },
    {
        "id": "pet_10",
        "name": "Lily",
        "age": "2",
        "sex": "female",
        "size": "medium",
        "photos": ["https://www.patasdacasa.com.br/sites/default/files/noticias/2020/02/7-sinais-que-mostram-que-seu-cachorro-e-muito-inteligente.jpg"],
        "weight": "6",
        "description": "Elegant white coat with a playful spirit",
        "behavior": "curious",
        "observations": "Loves exploring the backyard"
    },
    {
        "id": "pet_11",
        "name": "Oscar",
        "age": "3",
        "sex": "male",
        "size": "small",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ669ORGXqUzMLp2_uGlXHWLMwGqrurkA2ObQ&usqp=CAU"],
        "weight": "5",
        "description": "Dapple coat with a mischievous grin",
        "behavior": "energetic",
        "observations": "Enjoys agility training"
    },
    {
        "id": "pet_12",
        "name": "Zara",
        "age": "1",
        "sex": "female",
        "size": "large",
        "photos": ["https://img.nsctotal.com.br/wp-content/uploads/2023/05/Chow-chow-1024x683-1-e1683637233356.jpg"],
        "weight": "8",
        "description": "Sleek black coat with a gentle nature",
        "behavior": "calm",
        "observations": "Loves sunbathing in the yard"
    },
    {
        "id": "pet_13",
        "name": "Coco",
        "age": "4",
        "sex": "male",
        "size": "medium",
        "photos": ["https://img.freepik.com/fotos-gratis/filhote-de-cachorro-bichon-frise-fofo-posando-no-estudio_1303-27288.jpg"],
        "weight": "7",
        "description": "Brown coat with a wagging tail",
        "behavior": "friendly",
        "observations": "Enjoys car rides"
    },
    {
        "id": "pet_14",
        "name": "Molly",
        "age": "2",
        "sex": "female",
        "size": "small",
        "photos": ["https://img.nsctotal.com.br/wp-content/uploads/2023/11/Cachorro-praia.jpg"],
        "weight": "4",
        "description": "Fluffy white fur with a sweet demeanor",
        "behavior": "loving",
        "observations": "Loves being pampered"
    },
    {
        "id": "pet_15",
        "name": "Teddy",
        "age": "5",
        "sex": "male",
        "size": "large",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMfoGzR2puTWIXIHld6TfzSW7aM8qGe2h-TQ&usqp=CAU"],
        "weight": "11",
        "description": "Golden retriever with a friendly disposition",
        "behavior": "playful",
        "observations": "Enjoys playing in the water"
    },
    {
        "id": "pet_16",
        "name": "Ruby",
        "age": "3",
        "sex": "female",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTr-auIolrgTmwiMOysTMycMmLJP6CnE2bF-CCW1pxTJ-B7qjiWNPKjmK3NPDC6qqdOcEU&usqp=CAU"],
        "weight": "6",
        "description": "Red coat with a loving personality",
        "behavior": "gentle",
        "observations": "Enjoys belly rubs"
    },
    {
        "id": "pet_17",
        "name": "Bailey",
        "age": "1",
        "sex": "male",
        "size": "small",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRzk0PbRnHTsSqQHG52StFpRwLigus68cNl48puPxqjVD0lP4fBo9EOCRIEmJK7ZgRv1h0&usqp=CAU"],
        "weight": "5",
        "description": "Adorable with a playful spirit",
        "behavior": "energetic",
        "observations": "Loves chasing squirrels"
    },
    {
        "id": "pet_18",
        "name": "Lola",
        "age": "4",
        "sex": "female",
        "size": "large",
        "photos": ["https://jpimg.com.br/uploads/2024/01/10-racas-de-cachorro-que-mais-sofrem-com-o-calor.jpg"],
        "weight": "9",
        "description": "Spotted coat with a friendly wag",
        "behavior": "calm",
        "observations": "Enjoys sunbathing in the garden"
    },
    {
        "id": "pet_19",
        "name": "Duke",
        "age": "2",
        "sex": "male",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLjuOGNklAkPEw_VZdrrViUJWw2OppHj-ViA&usqp=CAU"],
        "weight": "8",
        "description": "Sturdy build with a playful attitude",
        "behavior": "loyal",
        "observations": "Loves fetch and tug-of-war"
    },
    {
        "id": "pet_20",
        "name": "Misty",
        "age": "1",
        "sex": "female",
        "size": "small",
        "photos": ["https://cdn.folhape.com.br/img/pc/1100/1/dn_arquivo/2019/09/quantas-horas-um-cachorro-dorme.jpg"],
        "weight": "3",
        "description": "Fluffy gray coat with a gentle nature",
        "behavior": "calm",
        "observations": "Enjoys bedtime cuddles"
    },
    {
        "id": "pet_21",
        "name": "Sammy",
        "age": "3",
        "sex": "male",
        "size": "large",
        "photos": ["https://gizmodo.uol.com.br/wp-content/blogs.dir/8/files/2019/09/cachorro-getty-images1.jpg"],
        "weight": "10",
        "description": "Sable coat with a friendly bark",
        "behavior": "playful",
        "observations": "Loves to chase balls"
    },
    {
        "id": "pet_22",
        "name": "Cupcake",
        "age": "2",
        "sex": "female",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzj-ZPdXoPiijTfdIFZAEL8NOdFWPNNnXNyA&usqp=CAU"],
        "weight": "6",
        "description": "Small and sweet with a loving personality",
        "behavior": "gentle",
        "observations": "Great with children"
    },
    {
        "id": "pet_23",
        "name": "Oliver",
        "age": "4",
        "sex": "male",
        "size": "small",
        "photos": ["https://petshopdopatinho.com.br/wp-content/uploads/2019/10/animal-blur-canine-551628.jpg"],
        "weight": "5",
        "description": "White coat with a playful demeanor",
        "behavior": "energetic",
        "observations": "Enjoys agility training"
    },
    {
        "id": "pet_24",
        "name": "Lily",
        "age": "1",
        "sex": "female",
        "size": "medium",
        "photos": ["https://www.montana.com.br/wp-content/uploads/2021/11/Problemas-com-o-xixi-do-seu-cachorro-nos-tecidos.jpg"],
        "weight": "7",
        "description": "Golden retriever with a friendly wag",
        "behavior": "loving",
        "observations": "Loves belly rubs"
    },
    {
        "id": "pet_25",
        "name": "Leo",
        "age": "5",
        "sex": "male",
        "size": "large",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb9FaS42R8us_znKTgUlsasuFNk2jcMpWTlw&usqp=CAU"],
        "weight": "12",
        "description": "Sleek black coat with a calm demeanor",
        "behavior": "calm",
        "observations": "Great with other pets"
    },
    {
        "id": "pet_26",
        "name": "Daisy",
        "age": "2",
        "sex": "female",
        "size": "small",
        "photos": ["https://super.abril.com.br/wp-content/uploads/2019/04/si_cachorroinstagram_home.png?w=720&h=440&crop=1"],
        "weight": "4",
        "description": "Adorable with a playful spirit",
        "behavior": "playful",
        "observations": "Loves to chase butterflies"
    },
    {
        "id": "pet_27",
        "name": "Hugo",
        "age": "3",
        "sex": "male",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKSjvnOnjfVGwgheckGiP07OZOYL_NHKngEQ&usqp=CAU"],
        "weight": "8",
        "description": "Brindle coat with a wagging tail",
        "behavior": "friendly",
        "observations": "Enjoys long walks"
    },
    {
        "id": "pet_28",
        "name": "Mocha",
        "age": "1",
        "sex": "female",
        "size": "large",
        "photos": ["https://pantanalpet.com.br/wp-content/uploads/2022/02/Conheca-as-Novas-Racas-de-Cachorros-Oficialmente-Reconhecidas.png"],
        "weight": "9",
        "description": "Brown coat with a sweet temperament",
        "behavior": "gentle",
        "observations": "Loves car rides"
    },
    {
        "id": "pet_29",
        "name": "Simba",
        "age": "4",
        "sex": "male",
        "size": "medium",
        "photos": ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwg44ix-L2zoDkniLwePpGCEp_Z0NGIlL8vA&usqp=CAU"],
        "weight": "7",
        "description": "Golden fur with a playful nature",
        "behavior": "energetic",
        "observations": "Enjoys playing in the snow"
    },
    {
        "id": "pet_30",
        "name": "Coco",
        "age": "2",
        "sex": "female",
        "size": "small",
        "photos": ["https://blog.matsudapet.com.br/wp-content/uploads/2021/02/shutterstock_1437575729-min-1.jpg"],
        "weight": "3",
        "description": "Fluffy white fur with a gentle demeanor",
        "behavior": "calm",
        "observations": "Loves being pampered"
    }
]